% Compute spectrogram

% Generated by MATLAB(R) 9.4 and Signal Processing Toolbox 8.0.
% Generated on: 20-Nov-2019 09:44:07

% Parameters
frequencyLimits = [0 1]; % Normalized frequency (*pi rad/sample)
timeResolution = 512; % samples
overlapPercent = 75;

%%
% Index into signal time region of interest
timeLimits = [1 46797]; % samples
data_ROI = data(:);
data_ROI = data_ROI(timeLimits(1):timeLimits(2));

% Compute spectral estimate
% Run the function call below without output arguments to plot the results
pspectrum(data_ROI, ...
    'spectrogram', ...
    'FrequencyLimits',frequencyLimits, ...
    'TimeResolution',timeResolution, ...
    'OverlapPercent',overlapPercent);

figure(2)
imshow(P)
